files:
  - source: /sources/project_locale/BasicNeeds/BasicNeeds.pot
    translation: >-
      /sources/project_locale/BasicNeeds/%locale_with_underscore%/LC_MESSAGES/BasicNeeds.po
  - source: >-
      /sources/project_locale/CommandLineArgumentsManagement/CommandLineArgumentsManagement.pot
    translation: >-
      /sources/project_locale/CommandLineArgumentsManagement/%locale_with_underscore%/LC_MESSAGES/CommandLineArgumentsManagement.po
