files:
  - source: /sources/project_locale/BasicNeeds/BasicNeeds.pot
    translation: >-
      /sources/project_locale/BasicNeeds/%locale_with_underscore%/LC_MESSAGES/BasicNeeds.po
  - source: >-
      /sources/project_locale/CommandLineArgumentsManagement/CommandLineArgumentsManagement.pot
    translation: >-
      /sources/project_locale/CommandLineArgumentsManagement/%locale_with_underscore%/LC_MESSAGES/CommandLineArgumentsManagement.po
  - source: /sources/project_locale/DataInputOutput/DataInputOutput.pot
    translation: >-
      /sources/project_locale/DataInputOutput/%locale_with_underscore%/LC_MESSAGES/DataInputOutput.po
  - source: /sources/project_locale/DataManipulator/DataManipulator.pot
    translation: >-
      /sources/project_locale/DataManipulator/%locale_with_underscore%/LC_MESSAGES/DataManipulator.po
  - source: /sources/project_locale/FileOperations/FileOperations.pot
    translation: >-
      /sources/project_locale/FileOperations/%locale_with_underscore%/LC_MESSAGES/FileOperations.po
  - source: /sources/project_locale/LocalizationsCommon/LocalizationsCommon.pot
    translation: >-
      /sources/project_locale/LocalizationsCommon/%locale_with_underscore%/LC_MESSAGES/LocalizationsCommon.po
  - source: /sources/project_locale/ParameterHandling/ParameterHandling.pot
    translation: >-
      /sources/project_locale/ParameterHandling/%locale_with_underscore%/LC_MESSAGES/ParameterHandling.po
  - source: /sources/project_locale/ProjectNeeds/ProjectNeeds.pot
    translation: >-
      /sources/project_locale/ProjectNeeds/%locale_with_underscore%/LC_MESSAGES/ProjectNeeds.po
  - source: >-
      /sources/project_locale/TableauHyperApiExtraLogic/TableauHyperApiExtraLogic.pot
    translation: >-
      /sources/project_locale/TableauHyperApiExtraLogic/%locale_with_underscore%/LC_MESSAGES/TableauHyperApiExtraLogic.po
  - source: >-
      /sources/project_locale/TableauServerCommunicator/TableauServerCommunicator.pot
    translation: >-
      /sources/project_locale/TableauServerCommunicator/%locale_with_underscore%/LC_MESSAGES/TableauServerCommunicator.po
  - source: /sources/project_locale/TypeDetermination/TypeDetermination.pot
    translation: >-
      /sources/project_locale/TypeDetermination/%locale_with_underscore%/LC_MESSAGES/TypeDetermination.po
